spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:purchase}
    username: ${DB_USER:purchase}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
  session:
    redis:
      namespace: session:purchase
  thymeleaf:
    cache: false
server:
  port: 8080
  shutdown: graceful
management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        health: "health"
      exposure:
        include: health
logging:
  level:
    root: info
    org.mybatis: debug
